elsa_endpoint_authority = "elsa-data.dev.umccr.org"
cache_location = "elsadatalocaldevtestinfr-tempprivatebucket3b80855-p9qoue91haoy"

ticket_server_cors_allow_headers = "All"
ticket_server_cors_allow_origins = [
    "https://elsa-data.dev.umccr.org",
    "https://elsa-data.umccr.org",
]
ticket_server_cors_allow_methods = "All"
ticket_server_cors_allow_credentials = true
ticket_server_cors_max_age = 300

data_server_enabled = false

name = "umccr-htsget-elsa-rs"
version = "0.1"
organization_name = "UMCCR"
organization_url = "https://umccr.org/"
contact_url = "https://umccr.org/"
documentation_url = "https://github.com/umccr/htsget-elsa-rs"
environment = "dev"

[[resolvers]]
regex = '^(umccr-10c-data-dev)/(?P<key>.*)$'
substitution_string = '$key'

[[resolvers]]
regex = '^(umccr-10f-data-dev)/(?P<key>.*)$'
substitution_string = '$key'

[[resolvers]]
regex = '^(umccr-10g-data-dev)/(?P<key>.*)$'
substitution_string = '$key'

[[resolvers]]
regex = '^(umccr-agha-test-dev)/(?P<key>.*)$'
substitution_string = '$key'

[[resolvers]]
regex = '^(umccr-research-dev)/(?P<key>.*)$'
substitution_string = '$key'

[[resolvers]]
regex = '^(umccr-primary-data-dev)/(?P<key>.*)$'
substitution_string = '$key'

[[resolvers]]
regex = '^(umccr-validation-prod)/(?P<key>.*)$'
substitution_string = '$key'
